repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: [--indent=4, --no-ensure-ascii, --no-sort-keys]