version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:24.0.5-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py3-pip=23.1.2-r0
            pip install \
              docker-compose==1.12.0 \
              ruff==0.3.5
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run static analysis
          command: |
            ruff check --fix --exit-non-zero-on-fix
            ruff format
      - run:
          name: Run tests
          command: |
            docker run --rm app python manage.py test
